# ========================================================================
# Blog personal settings
# ========================================================================

# Themes are encouraged to use these universal variables 
# so be sure to set them if your theme uses them. 
title : Maxint Lin
tagline : On My Way
author:
    name : Naiyang Lin (maxint)
    shortname: maxint
    # Encoded email address
    email : '&#108;&#110;&#121;&#099;&#104;&#105;&#110;&#097;&#064;&#103;&#109;&#097;&#105;&#108;&#046;&#099;&#111;&#109;'
    github : maxint
    weibo : maxint
    bitbucket : maxint

production_url : http://maxint.github.io
theme : default


# ========================================================================
# All jekyll-Bootstrap specific configuration
# ========================================================================
JB:
    # All links will be namespaced by BASE_PATH if defined
    BASE_PATH : false

    # By default, the ASSET_PATH is automatically defined relative to BASE_PATH
    # plus the enabled theme name.
    # ex: [BASE_PATH]/assets/themes/[THEME-NAME]
    #
    # Override this by defining an absolute path to assets here.
    # ex: 
    #   http://s3.amazonaws.com/yoursite/themes/watermelon/assets
    ASSET_PATH : false

    # Comments helper
    # Set 'provider' to the comment provider you want to use.
    # Set 'provider' to false to turn commneting off globally.
    comments :
        provider : disqus
        disqus :
            short_name : mgithub

    # Analytics helper
    analytics :
        provider : google
        google :
            tracking_id : 'UA-XXX-XX'

    # Sharing helper
    # Sharing is for things like tweet, plusone, like, reddit buttons etc.
    sharing:
        provider: false

    # Setting any helper's provider to 'custom' will bypass the helper code
    # and include your custom code. Your custom file must be defined at:
    #   ./_includes/custom/[HELPER]
    # where [HELPER] is the name of the helper you are overriding


# ========================================================================
# Jekyell system settings
# ========================================================================

# Global configuration
source : .
destination : ./_site
plugins : ./_plugins
layouts : ./_layouts
timezone : Aisa/Beijing
# for debug
safe: false

relative_permalinks : true
# This is the default format. 
# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks
#permalink : date
#permalink: /:categories/:year/:month/:day/:title 
paginate_path : 'page:num'

markdown : maruku
markdown_ext : markdown,mkd,mkdn,md
textile_ext : textile

# Serve settings
port: 4000
#host: HOSTNAME
#baseurl: URL
