# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# ========================================================================
# Site settings
# ========================================================================
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Maxint Lin
email: '&#108;&#110;&#121;&#099;&#104;&#105;&#110;&#097;&#064;&#103;&#109;&#097;&#105;&#108;&#046;&#099;&#111;&#109;'
description: >- # this means to ignore newlines until "baseurl:"
  Happy Coding
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://maxint.github.io" # the base hostname & protocol for your site, e.g. http://example.com
username: maxint
full_name: Naiyang Lin
github_username: maxint
theme: minima
# theme: jekyll-theme-awesome

# ========================================================================
# Jekyell system settings
# ========================================================================
# Build settings
markdown: kramdown
kramdown:
  input: GFM
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# ========================================================================
# All jekyll-Bootstrap specific configuration
# ========================================================================
JB:
  # All links will be namespaced by BASE_PATH if defined
  BASE_PATH: false

  # By default, the ASSET_PATH is automatically defined relative to BASE_PATH
  # plus the enabled theme name.
  # ex: [BASE_PATH]/assets/themes/[THEME-NAME]
  #
  # Override this by defining an absolute path to assets here.
  # ex: 
  #   http://s3.amazonaws.com/yoursite/themes/watermelon/assets
  ASSET_PATH: false

  # Comments helper
  comments:
    provider: uyan # false
    uyan:
      id: 1948160

  # Analytics helper
  analytics:
    provider: cnzz # false
    cnzz:
      tracking_id: '1254823254'

  # Sharing helper
  # Sharing is for things like tweet, plusone, like, reddit buttons etc.
  sharing:
    provider: false

  # Setting any helper's provider to 'custom' will bypass the helper code
  # and include your custom code. Your custom file must be defined at:
  #   ./_includes/custom/[HELPER]
  # where [HELPER] is the name of the helper you are overriding
